apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: default
spec:
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      serviceAccountName: site
      automountServiceAccountToken: false
      containers:
        - name: nginx
          image: ghcr.io/cdub-63/christian-wallace-site:838aed349f4b89d7c3a83f6918db209f7a77a0cd
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
