apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: nginx
          image: ghcr.io/cdub-63/christian-wallace-site:b48fc0ec71a3ba9ac66008de09d9b873cbf121bb
          ports:
            - containerPort: 80
