apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: christian-wallace-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cdub-63/christian-wallace.com
    targetRevision: HEAD
    path: manifests/site
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
